name: flutterapp0
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  groovin_material_icons: ^1.1.5
  flutter_webview_plugin: ^0.2.1
  image_picker: ^0.6.7
  shared_preferences: ^0.4.3
  event_bus: ^1.0.0
  barcode_scan: ^3.0.1
  http: ^0.12.0
  path_provider: ^0.4.1
  image: ^2.0.4
  fluro: ^1.3.4
  flutter_swiper: ^1.0.2
  charts_flutter: ^0.5.0
  cached_network_image: ^0.5.1
  video_player: ^0.10.11
  collection: ^1.14.11
  device_info: ^0.2.1
  intl: ^0.15.6
  connectivity: ^0.3.1
  shimmer: ^0.0.4
  pull_to_refresh: ^1.1.6
  fluttertoast: ^6.0.1
  sqljocky5: ^2.2.0
  sqflite: any
  flutter_cupertino_date_picker: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/ic_avatar_default.png
    - images/ic_nav_news_normal.png
    - images/ic_nav_news_actived.png
    - images/ic_nav_tweet_normal.png
    - images/ic_nav_tweet_actived.png
    - images/ic_nav_discover_normal.png
    - images/ic_nav_discover_actived.png
    - images/ic_nav_my_normal.png
    - images/ic_nav_my_pressed.png
    - images/ic_discover_gist.png
    - images/ic_discover_git.png
    - images/ic_discover_nearby.png
    - images/ic_discover_pos.png
    - images/ic_discover_scan.png
    - images/ic_discover_shake.png
    - images/ic_discover_softwares.png
    - images/ic_arrow_right.png
    - images/ic_my_blog.png
    - images/ic_my_message.png
    - images/ic_my_question.png
    - images/ic_my_recommend.png
    - images/ic_my_team.png
    - images/ic_test.png
    - images/ic_hongshu.jpg
    - images/ic_img_default.jpg
    - images/ic_comment.png
    - images/cover_img.jpg
    - images/leftmenu/ic_xiaoheiwu.png
    - images/leftmenu/ic_fabu.png
    - images/leftmenu/ic_about.png
    - images/leftmenu/ic_settings.png
    - images/ic_osc_logo.png
    - images/ic_add_pics.png
    - images/xialajiantou.png
    - images/fangkuai.png
    - images/guanli.png
    - images/bluequan.png
    - images/greyquan.png
    - images/zb.png
    - images/tongji.png

    - images/tqjl/
    - images/tqjl/xia_manager.png
    - images/tqjl/heise_xia_manager.png
    - images/tqjl/daiban_manager.png
    - images/tqjl/yiban_manager.png
    - images/tqjl/guanbi.png
    - images/tqjl/grey_sanjiao.png
    - images/tqjl/xiangji.png

    - images/tqjl/1.5x/grey_sanjiao.png
    - images/tqjl/1.5x/guanbi.png
    - images/tqjl/1.5x/heise_xia_manager.png
    - images/tqjl/1.5x/xiangji.png

    - images/tqjl/2.0x/daiban_manager.png
    - images/tqjl/2.0x/yiban_manager.png
    - images/tqjl/2.0x/xia_manager.png
    - images/tqjl/2.0x/heise_xia_manager.png
    - images/tqjl/2.0x/grey_sanjiao.png
    - images/tqjl/2.0x/guanbi.png
    - images/tqjl/2.0x/xiangji.png

    - images/tqjl/3.0x/grey_sanjiao.png
    - images/tqjl/3.0x/guanbi.png
    - images/tqjl/3.0x/xiangji.png
    - images/tqjl/3.0x/heise_xia_manager.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
